namespace: mgdis
name: ovh
version: 0.1.1
readme: README.md
authors:
- MGDIS
description: Cloud OVH collection to manage resources by API
license:
- GPL-2.0-or-later
tags:
- cloud
- ovh
# The URL of the originating SCM repository
repository: https://github.com/MGDIS/infra-ovh-ansible-module

# The URL to any online docs
documentation: https://github.com/MGDIS/infra-ovh-ansible-module

# The URL to the homepage of the collection/project
homepage: https://github.com/MGDIS/infra-ovh-ansible-module

# The URL to the collection issue tracker
issues: https://github.com/MGDIS/infra-ovh-ansible-module/issues

