namespace: mgdis
name: ovh
version: 0.1.0
readme: README.md
authors:
- MGDIS
description: Cloud OVH collection to manage resources by API
license:
- GPL-2.0-or-later
tags:
- cloud
- ovh
# The URL of the originating SCM repository
repository: http://example.com/repository

# The URL to any online docs
documentation: http://docs.example.com

# The URL to the homepage of the collection/project
homepage: http://example.com

# The URL to the collection issue tracker
issues: http://example.com/issue/tracker

