name: Releasing

on:
  release:
    types: [released]

env:
  VERSION: "0.1.0"

jobs:
  buildandpublish:
    runs-on: ubuntu-latest
    name: Lint
    steps:
      - name: Check out source repository
        uses: actions/checkout@v2
      - name: Set up Python environment
        uses: actions/setup-python@v1
        with:
          python-version: "3.8"
      - name: Build Ansible Collection
        run: ansible-galaxy collection build
      - name: Deploy Ansible collection to Galaxy
        run: ansible-galaxy collection publish mgdis-ovh-$VERSION.tar.gz --api-key ${{ secrets.ANSIBLE_GALAXY_API_KEY }}
