name: Releasing

on:
  release:
    types: [released]

jobs:
  buildandpublish:
    runs-on: ubuntu-latest
    name: Lint
    steps:
      - name: Check out source repository
        uses: actions/checkout@v2
      - name: Get current version
        id: cversion
        run: echo "::set-output name=version::$(grep version galaxy.yml | awk -F'"' '{ print $2 }')"
      - name: Set up Python environment
        uses: actions/setup-python@v1
        with:
          python-version: "3.8"
      - name: flake8 Lint
        uses: py-actions/flake8@v1
      - name: Build Ansible Collection
        run: ansible-galaxy collection build
      - name: Deploy Ansible collection to Galaxy
        run: ansible-galaxy collection publish mgdis-ovh-${{ steps.cversion.outputs.version }}.tar.gz --api-key ${{ secrets.ANSIBLE_GALAXY_API_KEY }}
